name = "SlomServer"
author = "Jyzzrd"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "915e3d7d9cba6b150c64b1298128b603cec75d821d0dadac6e2049cbc0f906ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
