name = "SlomServer"
author = "Jyzzrd"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2591a82d4d02163fdc080b1f0ab61e1bf65c9157ee85e1f5c7eb586bb4a5ecbe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
